//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamAutoCrack.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SteamAutoCrack.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 1. Generate Goldberg Steam Emulator Game Info 的本地化字符串。
        /// </summary>
        public static string _1GenerateGoldbergSteamEmulatorGameInfo {
            get {
                return ResourceManager.GetString("_1GenerateGoldbergSteamEmulatorGameInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2. Generate Goldberg Steam Emulator Configuration 的本地化字符串。
        /// </summary>
        public static string _2GenerateGoldbergSteamEmulatorConfiguration {
            get {
                return ResourceManager.GetString("_2GenerateGoldbergSteamEmulatorConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3. Unpack SteamStub 的本地化字符串。
        /// </summary>
        public static string _3UnpackSteamStub {
            get {
                return ResourceManager.GetString("_3UnpackSteamStub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4. Apply Goldberg Steam Emulator 的本地化字符串。
        /// </summary>
        public static string _4ApplyGoldbergSteamEmulator {
            get {
                return ResourceManager.GetString("_4ApplyGoldbergSteamEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5. Generate Crack Only Files 的本地化字符串。
        /// </summary>
        public static string _5GenerateCrackOnlyFiles {
            get {
                return ResourceManager.GetString("_5GenerateCrackOnlyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 6. Restore Crack 的本地化字符串。
        /// </summary>
        public static string _6RestoreCrack {
            get {
                return ResourceManager.GetString("_6RestoreCrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account Name: 的本地化字符串。
        /// </summary>
        public static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AppID Finder 的本地化字符串。
        /// </summary>
        public static string AppIDFinder {
            get {
                return ResourceManager.GetString("AppIDFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App Name: 的本地化字符串。
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot get app name from input path. 的本地化字符串。
        /// </summary>
        public static string CannotGetAppNameFromInputPath {
            get {
                return ResourceManager.GetString("CannotGetAppNameFromInputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking all goldberg emulator file exists or not... 的本地化字符串。
        /// </summary>
        public static string CheckingAllGoldbergEmulatorFileExistsOrNot {
            get {
                return ResourceManager.GetString("CheckingAllGoldbergEmulatorFileExistsOrNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Log 的本地化字符串。
        /// </summary>
        public static string ClearLog {
            get {
                return ResourceManager.GetString("ClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Crack Readme File 的本地化字符串。
        /// </summary>
        public static string CreateCrackReadmeFile {
            get {
                return ResourceManager.GetString("CreateCrackReadmeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Goldberg commitid:  的本地化字符串。
        /// </summary>
        public static string CurrentGoldbergSteamEmulatorCommitid {
            get {
                return ResourceManager.GetString("CurrentGoldbergSteamEmulatorCommitid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable Networking 的本地化字符串。
        /// </summary>
        public static string DisableNetworking {
            get {
                return ResourceManager.GetString("DisableNetworking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable Overlay 的本地化字符串。
        /// </summary>
        public static string DisableOverlay {
            get {
                return ResourceManager.GetString("DisableOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Empty AppID. Please select one using AppID Finder. 的本地化字符串。
        /// </summary>
        public static string EmptyAppIDPleaseSelectOneUsingAppIDFinder {
            get {
                return ResourceManager.GetString("EmptyAppIDPleaseSelectOneUsingAppIDFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Debug Log 的本地化字符串。
        /// </summary>
        public static string EnableDebugLog {
            get {
                return ResourceManager.GetString("EnableDebugLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error when selecting file: 的本地化字符串。
        /// </summary>
        public static string ErrorWhenSelectingFile {
            get {
                return ResourceManager.GetString("ErrorWhenSelectingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed 的本地化字符串。
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to Check goldberg emulator. 的本地化字符串。
        /// </summary>
        public static string FailedToCheckGoldbergEmulator {
            get {
                return ResourceManager.GetString("FailedToCheckGoldbergEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load App List. Please restart SteamAutoCrack to try again. 的本地化字符串。
        /// </summary>
        public static string FailedToLoadAppListPleaseRestartSteamAutoCrackToTryAgain {
            get {
                return ResourceManager.GetString("FailedToLoadAppListPleaseRestartSteamAutoCrackToTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folder 的本地化字符串。
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Force 的本地化字符串。
        /// </summary>
        public static string Force {
            get {
                return ResourceManager.GetString("Force", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Force Download 的本地化字符串。
        /// </summary>
        public static string ForceDownload {
            get {
                return ResourceManager.GetString("ForceDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Force Generate for each steam__api(64).dll 的本地化字符串。
        /// </summary>
        public static string ForceGenerateForEachSteam__api64Dll {
            get {
                return ResourceManager.GetString("ForceGenerateForEachSteam__api64Dll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Force Update Steam App List 的本地化字符串。
        /// </summary>
        public static string ForceUpdateSteamAppList {
            get {
                return ResourceManager.GetString("ForceUpdateSteamAppList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fuzzy Search 的本地化字符串。
        /// </summary>
        public static string FuzzySearch {
            get {
                return ResourceManager.GetString("FuzzySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate Achievement Images 的本地化字符串。
        /// </summary>
        public static string GenerateAchievementImages {
            get {
                return ResourceManager.GetString("GenerateAchievementImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate Steam Interfaces file 的本地化字符串。
        /// </summary>
        public static string GenerateSteamInterfacesFile {
            get {
                return ResourceManager.GetString("GenerateSteamInterfacesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generator API: 的本地化字符串。
        /// </summary>
        public static string GeneratorAPI {
            get {
                return ResourceManager.GetString("GeneratorAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Goldberg emulator file is missing. 的本地化字符串。
        /// </summary>
        public static string GoldbergEmulatorFileIsMissingNDownloadGoldbergEmulator1 {
            get {
                return ResourceManager.GetString("GoldbergEmulatorFileIsMissingNDownloadGoldbergEmulator1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Goldberg emulator? 的本地化字符串。
        /// </summary>
        public static string GoldbergEmulatorFileIsMissingNDownloadGoldbergEmulator2 {
            get {
                return ResourceManager.GetString("GoldbergEmulatorFileIsMissingNDownloadGoldbergEmulator2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep .bind Section 的本地化字符串。
        /// </summary>
        public static string KeepBindSection {
            get {
                return ResourceManager.GetString("KeepBindSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep DOS Stub Data 的本地化字符串。
        /// </summary>
        public static string KeepDOSStubData {
            get {
                return ResourceManager.GetString("KeepDOSStubData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language: 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level 的本地化字符串。
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Listen Port: 的本地化字符串。
        /// </summary>
        public static string ListenPort {
            get {
                return ResourceManager.GetString("ListenPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading... 的本地化字符串。
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log 的本地化字符串。
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message 的本地化字符串。
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offline Mode 的本地化字符串。
        /// </summary>
        public static string OfflineMode {
            get {
                return ResourceManager.GetString("OfflineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Config Folder 的本地化字符串。
        /// </summary>
        public static string OpenConfigFolder {
            get {
                return ResourceManager.GetString("OpenConfigFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Example Config 的本地化字符串。
        /// </summary>
        public static string OpenExampleConfig {
            get {
                return ResourceManager.GetString("OpenExampleConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Or get Steam AppID on 的本地化字符串。
        /// </summary>
        public static string OrGetSteamAppIDOn {
            get {
                return ResourceManager.GetString("OrGetSteamAppIDOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output Log to File 的本地化字符串。
        /// </summary>
        public static string OutputLogToFile {
            get {
                return ResourceManager.GetString("OutputLogToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output Path: 的本地化字符串。
        /// </summary>
        public static string OutputPath {
            get {
                return ResourceManager.GetString("OutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pack File With Zip Archive 的本地化字符串。
        /// </summary>
        public static string PackFileWithZipArchive {
            get {
                return ResourceManager.GetString("PackFileWithZipArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path:  的本地化字符串。
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Realign Sections 的本地化字符串。
        /// </summary>
        public static string RealignSections {
            get {
                return ResourceManager.GetString("RealignSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recalculate File Checksum 的本地化字符串。
        /// </summary>
        public static string RecalculateFileChecksum {
            get {
                return ResourceManager.GetString("RecalculateFileChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore to Default Config 的本地化字符串。
        /// </summary>
        public static string RestoreToDefaultConfig {
            get {
                return ResourceManager.GetString("RestoreToDefaultConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Config File 的本地化字符串。
        /// </summary>
        public static string SaveConfigFile {
            get {
                return ResourceManager.GetString("SaveConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Searching... 的本地化字符串。
        /// </summary>
        public static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Folder or File? 的本地化字符串。
        /// </summary>
        public static string SelectFolderOrFile {
            get {
                return ResourceManager.GetString("SelectFolderOrFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source 的本地化字符串。
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam AppID: 的本地化字符串。
        /// </summary>
        public static string SteamAppID {
            get {
                return ResourceManager.GetString("SteamAppID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam Game Automatic Cracker 的本地化字符串。
        /// </summary>
        public static string SteamGameAutomaticCracker {
            get {
                return ResourceManager.GetString("SteamGameAutomaticCracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam ID: 的本地化字符串。
        /// </summary>
        public static string SteamID {
            get {
                return ResourceManager.GetString("SteamID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam Web API Key: 的本地化字符串。
        /// </summary>
        public static string SteamWebAPIKey {
            get {
                return ResourceManager.GetString("SteamWebAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update/Download 的本地化字符串。
        /// </summary>
        public static string UpdateDownload {
            get {
                return ResourceManager.GetString("UpdateDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Custom Broadcast IP: 的本地化字符串。
        /// </summary>
        public static string UseCustomBroadcastIP {
            get {
                return ResourceManager.GetString("UseCustomBroadcastIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Custom Save Location: 的本地化字符串。
        /// </summary>
        public static string UseCustomSaveLocation {
            get {
                return ResourceManager.GetString("UseCustomSaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Experimental Features 的本地化字符串。
        /// </summary>
        public static string UseExperimentalFeatures {
            get {
                return ResourceManager.GetString("UseExperimentalFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Experimental version Goldberg Emulator 的本地化字符串。
        /// </summary>
        public static string UseExperimentalVersionGoldbergEmulator {
            get {
                return ResourceManager.GetString("UseExperimentalVersionGoldbergEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Steam Web App List 的本地化字符串。
        /// </summary>
        public static string UseSteamWebAppList {
            get {
                return ResourceManager.GetString("UseSteamWebAppList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Xan105 API 的本地化字符串。
        /// </summary>
        public static string UseXan105API {
            get {
                return ResourceManager.GetString("UseXan105API", resourceCulture);
            }
        }
    }
}
